name: breaking_news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  provider: ^6.0.5
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.3
  auto_route: ^5.0.4
#  freezed_annotation: ^2.2.0
  get: 4.6.5
  equatable: ^2.0.5
  tuple: ^2.0.1
  dart_mappable: ^2.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  injectable_generator: ^2.1.4
  auto_route_generator: ^5.0.3
#  freezed: ^2.3.2
  flutter_test: 
    sdk: flutter
  dart_mappable_builder: ^2.0.2

flutter: 
  uses-material-design: true

